# Generated by Django 5.1.15 on 2026-07-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_cashtransaction_transaction_type'),
        ('payments', '0001_initial'),
        ('purchases', '0003_purchaseorder_purchaseorderitem_and_more'),
        ('sales', '0002_returns'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('purchase__isnull', True), ('sale__isnull', False)), models.Q(('purchase__isnull', False), ('sale__isnull', True)), _connector='OR'), name='paymentallocation_exactly_one_target'),
        ),
    ]
