# Generated by Django 5.1.15 on 2026-07-25 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_seed_chart_of_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_sales', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('customer_cash_payments', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('other_cash_income', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('cash_purchases', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('supplier_cash_payments', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('expenses', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('withdrawals', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expected_cash', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('actual_cash', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('difference', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
