# Generated by Django 5.1.15 on 2026-07-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_seed_safe_and_owner_capital_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('opening_float', 'Opening Float'), ('owner_funding', 'Owner Funding'), ('owner_withdrawal', 'Owner Withdrawal'), ('bank_to_register', 'Bank → Register'), ('register_to_bank', 'Register → Bank'), ('safe_to_register', 'Safe → Register'), ('register_to_safe', 'Register → Safe (Cash Drop)')], max_length=20),
        ),
    ]
