# Generated by Django 5.1.15 on 2026-07-25 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_cashtransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.cashregister'),
        ),
    ]
