# Generated by Django 5.1.15 on 2026-07-25 05:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_seed_default_warehouse'),
        ('products', '0002_pricing_redesign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='reference_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('purchase_return', 'Purchase Return'), ('sales_return', 'Sales Return'), ('adjustment', 'Adjustment'), ('transfer', 'Transfer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase_in', 'Purchase In'), ('sale_out', 'Sale Out'), ('sales_return_in', 'Sales Return In'), ('purchase_return_out', 'Purchase Return Out'), ('damage_out', 'Damage Out'), ('lost_out', 'Lost Out'), ('adjustment_in', 'Adjustment In'), ('adjustment_out', 'Adjustment Out'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['reference_type', 'reference_id'], name='inventory_i_referen_ace22e_idx'),
        ),
    ]
