# Generated by Django 5.1.15 on 2026-07-25 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_transaction_types_and_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.productbatch')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_stocks', to='inventory.warehouse')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='batchstock_quantity_gte_0')],
                'unique_together': {('batch', 'warehouse')},
            },
        ),
    ]
