# Generated by Django 5.1.15 on 2026-07-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_backfill_batchstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
