# Generated by Django 5.1.15 on 2026-07-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('price_change', 'Price Change'), ('stock_adjustment', 'Stock Adjustment'), ('payment', 'Payment'), ('sale_return', 'Sale Return'), ('purchase_return', 'Purchase Return'), ('login', 'Login'), ('logout', 'Logout'), ('failed_login', 'Failed Login'), ('role_change', 'Role Change'), ('stock_transfer', 'Stock Transfer'), ('day_closing', 'Day Closing'), ('cash_register_transaction', 'Cash Register Transaction'), ('cancel', 'Cancel'), ('balance_adjustment', 'Balance Adjustment')], max_length=30),
        ),
    ]
