# Generated by Django 5.1.15 on 2026-07-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='My General Store', max_length=150)),
                ('owner_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('invoice_footer', models.CharField(blank=True, default='Thank you for shopping with us!', max_length=255)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('currency', models.CharField(default='PKR', max_length=10)),
            ],
            options={
                'verbose_name': 'Store Settings',
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
