# Generated by Django 5.1.15 on 2026-07-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_storesettings_from_email_storesettings_smtp_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='brevo_api_key',
            field=models.CharField(blank=True, help_text='From brevo.com (free tier) — used instead of SMTP below when set, since most hosts block outgoing SMTP.', max_length=255),
        ),
    ]
