# Generated by Django 5.1.15 on 2026-07-26 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_storesettings_brevo_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storesettings',
            name='brevo_api_key',
        ),
    ]
