# Generated by Django 5.1.15 on 2026-07-25 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_payment_register'),
        ('sales', '0002_returns'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='finance.cashregister'),
        ),
    ]
