# Generated by Django 5.1.15 on 2026-07-25, hand-reordered so the old
# selling_price/wholesale_price/tax_percent/active columns are copied into
# their new homes (ProductPrice rows, a real Tax row, Product.status) before
# being dropped — no data loss on existing products.

import django.db.models.deletion
from django.db import migrations, models


def copy_old_pricing_data(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    ProductPrice = apps.get_model('products', 'ProductPrice')
    PriceLevel = apps.get_model('masters', 'PriceLevel')
    Tax = apps.get_model('masters', 'Tax')

    retail_level = PriceLevel.objects.filter(name='Retail').first()
    wholesale_level = PriceLevel.objects.filter(name='Wholesale').first()

    for product in Product.objects.all():
        if retail_level and product.selling_price:
            ProductPrice.objects.get_or_create(
                product=product, price_level=retail_level, defaults={'price': product.selling_price}
            )
        if wholesale_level and product.wholesale_price:
            ProductPrice.objects.get_or_create(
                product=product, price_level=wholesale_level, defaults={'price': product.wholesale_price}
            )
        if product.tax_percent:
            tax, _ = Tax.objects.get_or_create(
                name=f'{product.tax_percent}%', defaults={'rate': product.tax_percent}
            )
            product.tax_id = tax.id
        product.status = 'active' if product.active else 'inactive'
        product.save(update_fields=['tax', 'status'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_seed_price_levels'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('discontinued', 'Discontinued')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='masters.tax'),
        ),
        migrations.CreateModel(
            name='ProductBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=64, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='products.product')),
            ],
            options={
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sku', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_prices', to='masters.pricelevel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product')),
            ],
            options={
                'ordering': ['price_level__name'],
                'unique_together': {('product', 'price_level')},
            },
        ),
        migrations.RunPython(copy_old_pricing_data, noop_reverse),
        migrations.RemoveField(
            model_name='product',
            name='active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax_percent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wholesale_price',
        ),
    ]
